homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 50.812655
  longitude: 3.251111
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 31.325
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Brussels

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
#sun:

#Tracking
    
# Weather Prediction
sensor:
    platform: darksky
    api_key: e7d133b1a4fd98617b5be8bf1050fcd1
    monitored_conditions:
      - summary
      - temperature
      #- humidity
      #- ozone
      - hourly_summary
      #- daily_summary
      #- temperature_max
      #- temperature_min
      
      
#media 
media_player:
  - platform: onkyo
    host: 192.168.1.200
    name: ONKYO NR656

# Text to speech
tts:
platform: google

